openapi: 3.0.0
info:
  title: Auth Service API
  version: 1.0.0
servers:
  - url: /api
paths:
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
                firstName:
                  type: string
                lastName:
                  type: string
              required:
                - username
                - password
                - email
                - firstName
                - lastName
      responses:
        '200':
          description: User registered
  /superadmin:
    post:
      summary: Create the first super admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
                firstName:
                  type: string
                lastName:
                  type: string
              required:
                - username
                - password
                - email
                - firstName
                - lastName
      responses:
        '200':
          description: Super admin created
  /login:
    post:
      summary: Log in
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: Logged in
  /logout:
    post:
      summary: Log out
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
              required:
                - refreshToken
      responses:
        '200':
          description: Logged out
  /refresh:
    post:
      summary: Refresh access token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
              required:
                - refreshToken
      responses:
        '200':
          description: Token refreshed
  /profile:
    get:
      summary: Get current user profile
      responses:
        '200':
          description: Profile information
    patch:
      summary: Update profile
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                username:
                  type: string
                firstName:
                  type: string
                lastName:
                  type: string
                profilePicture:
                  type: string
                  format: binary
      responses:
        '200':
          description: Profile updated
    delete:
      summary: Delete profile
      responses:
        '200':
          description: Account deleted
  /user/organizations:
    get:
      summary: List organizations for the current user
      responses:
        '200':
          description: Organization list
  /password/change:
    post:
      summary: Change password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                oldPassword:
                  type: string
                newPassword:
                  type: string
              required:
                - oldPassword
                - newPassword
      responses:
        '200':
          description: Password changed
  /password/forgot:
    post:
      summary: Request password reset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
              required:
                - username
      responses:
        '200':
          description: Token created
  /password/reset:
    post:
      summary: Reset password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                newPassword:
                  type: string
              required:
                - token
                - newPassword
      responses:
        '200':
          description: Password reset
  /organizations:
    post:
      summary: Create organization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        '200':
          description: Organization created
    get:
      summary: List organizations
      responses:
        '200':
          description: Organization list
  /organizations/{id}/members:
    post:
      summary: Add member to organization
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                roleId:
                  type: string
              required:
                - userId
      responses:
        '200':
          description: Member added
  /organizations/{id}/members/{userId}:
    delete:
      summary: Remove member from organization
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Member removed
  /organizations/{id}/invite:
    post:
      summary: Invite user to organization
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                role:
                  type: string
              required:
                - email
      responses:
        '200':
          description: Invite created
  /organizations/{id}/invites:
    get:
      summary: List invites for organization
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Invite list
  /organizations/{id}:
    delete:
      summary: Delete organization
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Organization deleted
    patch:
      summary: Update organization
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Organization updated
  /users:
    get:
      summary: List users
      parameters:
        - in: query
          name: orgId
          schema:
            type: string
      responses:
        '200':
          description: Users list
  /users/{id}:
    delete:
      summary: Delete user
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User deleted
  /users/{id}/roles:
    post:
      summary: Update user roles
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                roleIds:
                  type: array
                  items:
                    type: string
              required:
                - roleIds
      responses:
        '200':
          description: Roles updated
  /roles:
    get:
      summary: List roles
      parameters:
        - in: query
          name: orgId
          schema:
            type: string
      responses:
        '200':
          description: Roles list
    post:
      summary: Create role
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                name:
                  type: string
                orgId:
                  type: string
              required:
                - code
                - orgId
      responses:
        '200':
          description: Role created
  /roles/{id}:
    patch:
      summary: Update role
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                name:
                  type: string
      responses:
        '200':
          description: Role updated
    delete:
      summary: Delete role
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Role deleted
  /invites:
    get:
      summary: List all invites
      responses:
        '200':
          description: Invite list
  /invites/{id}:
    delete:
      summary: Delete invite
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Invite deleted
  /my-invites:
    get:
      summary: List invites for current user
      responses:
        '200':
          description: Invite list
  /invites/{id}/accept:
    post:
      summary: Accept invite
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
              required:
                - token
      responses:
        '200':
          description: Invite accepted
  /transfer:
    post:
      summary: Transfer currency
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                toUsername:
                  type: string
                amount:
                  type: number
                orgId:
                  type: string
              required:
                - toUsername
                - amount
                - orgId
      responses:
        '200':
          description: Transfer complete
  /balance:
    get:
      summary: Get user balance
      parameters:
        - in: query
          name: orgId
          schema:
            type: string
      responses:
        '200':
          description: Balance information
